### ISSUE TITLE
Erik: a bit late, but here are a few nits

### ISSUE THREAD

**Issue by Mike-Heard** [tsvwg/draft-udp-options-dplpmtud#30]
From https://mailarchive.ietf.org/arch/msg/tsvwg/_bX84hMEyYY6yaOnt91HylY8lJ0/:

  * Section 3.2 on page 6 refers to wrong section of
    I-D.ietf-tsvwg-udp-options for EOL:

        (Section 9.1 of [I-D.ietf-tsvwg-udp-options])
    --->
        (Section 11.1 of [I-D.ietf-tsvwg-udp-options])

  * Section 4.2 on page 8 uses "Maximum Segment Size" / "MSS" instead of
    "Maximum Datagram Size" / "MDS":

        ...When the remote endpoint advertises a UDP Maximum
        Segment Size (MSS) option,...
    --->
        ...When the remote endpoint advertises a UDP Maximum
        Datagram Size (MDS) option,...

  * Section 4.4 on page 9 has a wrong section reference for the UDP
    Options API:

        ...(Section 13 of
        [I-D.ietf-tsvwg-udp-options]).
    --->
        ...(Section 15 of
        [I-D.ietf-tsvwg-udp-options]).

**Comment by gorryfair** [comment]
Good points, a cross-check of refs to the latest UDP Options seems needed.

**Comment by Mike-Heard** [comment]
_[ Erik sent this to the tsvwg list, but I do not see it in the archive_ ]

Hi Mike,

the first and third issues are still open (section numbers in the
UDP Options draft have increased since the last adjustment of those
in draft-ietf-tsvwg-udp-options-dplpmtud -- possibly because of the
addition of the two early sections "UDP Option Intended Uses" and "UDP
Option Design Principles").

The second issue, paraphrased "s/MSS/MDS/", is addressed in -12.

Thanks,
Erik

**Comment by gorryfair** [comment]
Assuming UDP Options is now stable: I now made a PR that also updates section numbers for UDP Options, which someone may like to check.

Gorry
